# Generated by Django 6.0.6 on 2026-10-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.person')),
                ('student_id', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
            ],
            bases=('model.person',),
        ),
    ]
