# Generated by Django 6.0.6 on 2026-10-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
