# Generated by Django 6.0.6 on 2026-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
    ]
