# Generated by Django 6.0.6 on 2026-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
